kbnm: install_host, look for kbnm binary in GOPATH

diff --git a/go/kbnm/install_host b/go/kbnm/install_host
--- a/go/kbnm/install_host
+++ b/go/kbnm/install_host
@@ -46,7 +46,17 @@ install() {
   fi
 
   local here="$(dirname $(realpath "$BASH_SOURCE"))"
-  local host_path="$(which kbnm || echo "$here/kbnm")"
+  local host_path="$(which "kbnm" || echo "$here/kbnm")"
+
+  if [[ ! -x "$host_path" ]]; then
+    # Is it in GOPATH, but not PATH?
+    host_path="$GOPATH/bin/kbnm"
+  fi
+
+  if [[ ! -x "$host_path" ]]; then
+    echo "failed to find kbnm executable, make sure it's in your \$PATH."
+    exit 2
+  fi
 
   echo "Writing: $target"
   cat "$here/host_json.template" \
